const simport = require('sequelize-import')

const baseModel = {
    // True if the model has a non-autogenerated primary key
    hasPrimaryKey() {
        const primaryKeys = Object.keys(this.attributes).filter((x) => {
            return this.attributes[x].primaryKey && !this.attributes[x]._autoGenerated
        })

        return primaryKeys.length > 0
    },

    // Uses true "upsert" if the model has a primary key, otherwise findOrCreate().
    bulkUpsert(rows) {
        if (!(rows instanceof Array)) console.error('Non array bulkUpsert argument!', typeof rows, rows instanceof Array, rows)
        return Promise.all(rows.map((row) => {
            if (this.hasPrimaryKey()) return this.upsert(row)
            else return this.findOrCreate({ where: row, defaults: row })
        }))
    }
}

export { baseModel }

export default {
    import(database) {
        // Import database models from current directory using simport
        this.models = simport(__dirname, database, { exclude: ['index.js'] })

        let counter = 0

        // Build relations between models
        Object.keys(this.models).forEach((modelName) => {
            if ('associate' in this.models[modelName]) {
                this.models[modelName].associate(this.models)
                counter++
            }

            // Spacing trick for console output
            let spaces = ''
            const spacesCount = (16 - modelName.length)
            for (let i = 0; i < spacesCount; i++) {
                spaces = spaces.concat(' ')
            }

            console.log(`${colors.yellow(modelName)} ${spaces} model imported`)
        })

        console.log('--------------------------------')
        console.log(`Built relations between ${colors.yellow(counter)} models`)

        return this.models
    },

    /**
     * Database tables represented as JavaScript objects
     */
    models: null
}
